### ISSUE TITLE
Support [@@deriving-like] for function definitions, not just types

### ISSUE THREAD

**Issue by aryx** [ocaml-ppx/ppxlib#168]
I used to have a ppx extension replacing
let foo a b = ...
[@@interactive]

in
let foo a b = 
let _ = Interactive.add_function "foo"

The code is there: https://github.com/aryx/fork-efuns/blob/master/ppx/ppx_interactive.ml

I was using ocaml-migrate-parsetree for that, but it seems its direct use for ppx is marked as deprecated and they advise people to switch to ppxlib.
Moreover, I have trouble using this PPX extension in a project using dune (which seems to accept
only a certain kinds of PPX extensions, mainly the one using ppxlib).

I could not find a way to port my extension to ppxlib, which provides only [@@deriving] for type definition, not function definition.

Any advice to port my PPX profiling extension to the latest-way-to-do?

**Comment by NathanReb** [comment]
The `Context_free.Rule` module contains the more generic API we use internally to provide ways to write `@@deriving` plugins but at the moment it doesn't support attributes attached to arbitrary structure items. We could probably extend it so that it supports value bindings along with the rest of the structure/signature items.

In the meantime you can also port your ppx using `Ppxlib.Driver.register_transformation ~impl` where `impl` is a `structure -> structure`. The code will probably be very similar to what you had originally except that if you need to recursively traverse the ast
you'd use the classes defined in `Ast_traverse` instead of an `Ast_mapper.t`.

If you need further help with this I'm happy to point you to other OMP-based ppx-es we recently ported!

**Comment by aryx** [comment]
Did things change regarding [@@deriving] for function definition? I manage to avoid switching
from ocaml-migrate-parsetree to ppxlib, but now most of the libraries I'm using depends on ppx_deriving > 5, so
seems like I have to migrate too to ppxlib ...

**Comment by aryx** [comment]
I could use some examples of OMP-based ppx-es you recently ported.
Here is the OMP-based ppx I am trying to port: https://github.com/returntocorp/pfff/blob/develop/ppx/ppx_profiling.ml
it's attaching a [[@profiling] to functions.

**Comment by aryx** [comment]
Ok, I managed to partially update my ppx extension (I just miss the AST_traverse, but I can add that later).
I guess it makes more sense to restrict [@@deriving] to type definitions.
