### ISSUE TITLE
Custom `argv` in Ppxlib.Driver.standalone?

### ISSUE THREAD

**Issue by anmonteiro** [ocaml-ppx/ppxlib#219]
Would a PR adding an `argv` argument to the `standalone` function in `Driver` be a welcome addition (in the style of https://github.com/ocaml-ppx/ocaml-migrate-parsetree/pull/82)?

I was working on porting a BuckleScript PPX to ppxlib and came across this apparent limitation vs Migrate_parsetree. Is there a way to do it that I didn't find?

**Comment by NathanReb** [comment]
Adding such an option shouldn't be necessary. Bucklescript should work with the `Driver.run_as_ppx_rewriter` driver as of `ppxlib.0.21.0`.

We added the right features there so `bisect_ppx` could still be used with Bucklescript, you can take a look at the [`bisect_ppx` port](https://github.com/aantron/bisect_ppx/pull/327) to see how we did it there, in particular how we ported the [bucklescript driver](https://github.com/aantron/bisect_ppx/pull/327/files#diff-a0f14c67cd37422f9b798953290c9c4a8113177c42587377183778adf19b6c31R1).

If for some reason that turns out not to work out for you, I'm happy to look into it but I'd like to avoid adding an `~argv` argument.

**Comment by anmonteiro** [comment]
It seems like that does indeed work. I'll report back if this changes or I run into an actual limitation. Thanks!
