### ISSUE TITLE
Release plan

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml-ppx/ppxlib#253]
Given the current state of ppxlib master (many packages are broken downstream when using it for different reasons) I am wondering if it would not be more prudent to backport a handful of fixes (e.g. https://github.com/ocaml-ppx/ppxlib/pull/242 and https://github.com/ocaml-ppx/ppxlib/pull/247 on top of my head) + the OCaml 4.13 support on top of ppxlib.0.22.0 and make it ppxlib.0.23.0.
Then continue working on master and release the next major version later.

This is just my educated guess based on what I'm seeing and past experiences. I'm hoping to avoid having to wait for things to get fixed to release OCaml 4.13 and put more stress on the ppxlib devs than needed.

**Comment by kit-ty-kate** [comment]
cc @pitag-ha

**Comment by pitag-ha** [comment]
Sorry for the delay in answering (I was on vacation). And by the way, thanks for all your help with this!

I'd like to release as soon as possible, particularly because of [the bug messing up parse errors](https://github.com/ocaml-ppx/ppxlib/issues/221) and for the 4.13 support. If we can't/shouldn't release "as normal" (which I think is the case), what you're saying sounds like a good idea to me. To clarify, I think the packages that are broken downstream are
-  4 packages I've sent patches to (the latter 2 just now): [patch](https://github.com/janestreet/ppx_variants_conv/pull/9) to `ppx_variants_conv`, [patch](https://github.com/janestreet/ppx_variants_conv/pull/9) to `ppx_accessor`, [patch](https://github.com/janestreet/ppx_optcomp/pull/14) to `ppx_optcomp`, [patch](https://gitlab.inria.fr/fpottier/visitors/-/merge_requests/5) to `visitors`
- `ocamlformat`: I've discussed that with @gpetiot and he's fixed the problem by [dropping the ppxlib dependency in ocamlformat](https://github.com/ocaml-ppx/ocamlformat/pull/1669)
- any package building with `jbuilder`. That probably only effects old downstream versions. Yet, fixing that might take a while.

Am I missing package(s)?

**Comment by pitag-ha** [comment]
I'm closing this since those releases have already been done now. Thanks for your help, @kit-ty-kate!
