### ISSUE TITLE
ppxlib master can't mix with other types of ppx derivers anymore

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml-ppx/ppxlib#254]
For instance, using ppxlib master to build the latest version of pgocaml_ppx:
```
#=== ERROR while compiling pgocaml_ppx.4.2.2 ==================================#
# context              2.1.0~beta4 | linux/x86_64 | ocaml-base-compiler.4.12.0 | file:///home/opam/opam-repository
# path                 ~/.opam/4.12.0/.opam-switch/build/pgocaml_ppx.4.2.2
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p pgocaml_ppx -j 31
# exit-code            1
# env-file             ~/.opam/log/pgocaml_ppx-15-f6baaa.env
# output-file          ~/.opam/log/pgocaml_ppx-15-f6baaa.out
### output ###
# File "ppx/dune", line 6, characters 4-54:
# 6 |     (pps ppx_tools_versioned.metaquot_408 ppx_optcomp))
#         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: Too many incompatible ppx drivers were found: ocaml-migrate-parsetree
# and ppxlib.
```
I think this is a similar issue to #251

**Comment by NathanReb** [comment]
I believe this has been true for a long while now: `ppx_tools_versioned` uses the OMP1 driver, while ppxlib now use the ppxlib, OMP2 based driver.

I don't think it can be considered a bug here. To be honest I'm even surprised you managed to install both since they depend on conflicting versions of OMP as far as I can tell. How did you build this with ppxlib's master?

**Comment by kit-ty-kate** [comment]
Ah that's true, my bad. I was using a custom opam file that has the dependency on OMP removed (since it does not depend on it anymore). I've opened https://github.com/ocaml-ppx/ppxlib/pull/255 to fix this issue more broadly upstream.
