### ISSUE TITLE
Suggestion to redeploy the gh-pages with sherlodoc enabled

### ISSUE THREAD

**Issue by mbarbin** [ocaml-ppx/ppxlib#533]
Before I forget, I noticed there's not search bar in https://ocaml-ppx.github.io/ppxlib/ppxlib/index.html.

I'm under the impression that if you have the sherlodoc package installed when you run `dune-release` then you'll get the search functionality enabled.

Would this enable a search on all the text pages of the manual in addition to the API pages? If so, that'd be a pretty nice low-hanging fruit!

- Suggestion to re-deploy the current version with `sherlodoc` enabled
- Consider whether more changes can help future proofing, such as adding `sherlodoc` as a `with-dev-setup` dep for the project?

**Comment by panglesd** [comment]
Unfortunately, I don't think sherlodoc searches in manual pages, although odoc gives it the possibility to do so!

I can confirm that having sherlodoc installed in the switch when running `dune-release` will enable the search functionality.

Also, I'm not sure whether we really want to host our own github pages with the docs, or if we want to link to the [ocaml.org version](https://ocaml.org/p/ppxlib/latest/doc/index.html). (Actually, I think it's better to link to the ocaml.org one, since it has links to the dependencies: eg compare the links for `Ocaml_common` in [this](https://ocaml-ppx.github.io/ppxlib/ppxlib/Astlib/Location/index.html#type-loc) and [that](https://ocaml.org/p/ppxlib/latest/doc/Astlib/Location/index.html#type-loc.loc).)

**Comment by mbarbin** [comment]
Thanks for linking the doc on `ocaml.org`. It sounds like you could probably decide to remove the gh-pages step and replace the GitHub pages with a link to the `ocaml.org` one. That makes sense to me. Another benefit of `ocaml.org`, is that it seems to support ways to browse the documentation for several versions, not only the one that was published last. I'm thinking that this can be helpful to folks running older versions.

Given that enabling the search in manual pages is not as simple as I thought, I will be closing this particular issue. Thanks for looking into it, and letting me know about the current behavior of sherlodoc in manual pages!
