### ISSUE TITLE
Context dependent extensions

### ISSUE THREAD

**Issue by NathanReb** [ocaml-ppx/ppxlib#65]
I'm currently trying to write a ppx extension that would be rewritten to the fully qualified path of the value it appears in (see https://github.com/NathanReb/ppx_there).

It seems that the right way to do that currently is to use `Ppxlib.Driver.register_transformation ~impl:my_expand_function` because I need some context to actually rewrite the extension node.

I looked into `Extension` though and found out about `Extension.Expert`. I'm not quite sure I got this right but I have the impression that for now the only thing it allows me to do is to verify the payload fits the declared `Ast_pattern.t` and if so get the payload node.

I was wondering if there were more helpers for such ppx plugins provided by `ppxlib` as I feel like I'm gonna redo a lot of the work that's already done here.

**Comment by diml** [comment]
What about the `path` argument given the the callback in `Extension.declare`? Isn't that exactly what you want?

**Comment by NathanReb** [comment]
I tried that already but it seems that `path` is the `.ml` or `.mli` file path. To clarify, what I'm trying to achieve here is to rewrite:
```ocaml
module B = struct
  let c = [%there]
end
```
into:
```ocaml
module B = struct
  let c = "A.B.c"
end
```
assuming it sits in `a.ml`. It's actually more likely to look like that:
```ocaml
module B = struct
  let c = __MODULE__ ^ ".B.c"
end
```
but that doesn't really matter here.

**Comment by diml** [comment]
I see. Ideally, the path should be abstract and carry enough information for this purpose. We could change the implementation of ppxlib to do that, and expose the new type as an `Extenstion.declare_v2` function

**Comment by NathanReb** [comment]
That'd be great indeed. I think it'd be much more profitable that I actually contribute that to `ppxlib` and use the new feature to write `ppx_there` rather than to re-invent the wheel on my side.

I can also see deriving plugins benefit from that as the use case I have for `ppx_there` is mostly producing error messages, which derived functions might have to do as well. Being able to that using `path` would probably encourage authors to improve error reporting in derived functions.

**Comment by NathanReb** [comment]
I'll have a go at it, any pointers or suggestions you might have are as usual welcome!

**Comment by diml** [comment]
Sounds good. For the pointers, I suggest to start with by adding a new module to represent the path. For instance `Code_path`. Then you can duplicate the class `Ast_traverse.map_with_path` and make it use the new type. You will have to override a few more methods to handle more language constructions such as functions. Then you can inherit this new class instead of `map_with_path` in context_free.ml.

Then, you will have to update the functions `Extension.For_context.convert` to take the new path type rather than `path:string`. You can break the API of these functions as I don't believe they are used outside of ppxlib. You will also need to change the `path:string` to `path:Code_path.t` in `module M = Make(struct ... end)` in extension.ml. Then, you can rename `declare` to `declare_v2` and add a `declare` function that translate `Code_path.t` to a string before passing it to the callback.

You will also need to do similar changes in `Deriving`. You can break the API of `Generator.apply` as well.

**Comment by NathanReb** [comment]
After having a first look at the code I was a little confused and couldn't understand why path wouldn't contain the module path as `map_with_path`'s implementation suggested. It turns out that it does but it concatenates the "internal module path" to the file path. To clarify, if you expand the `ext` extension in the following code:
```ocaml
let top_level = [%ext]

module A = struct
  let in_submodule = [%ext]
end
```
in a `some/path/file.ml` file, the `expand` function will be called with `"some/path/file.ml"` in `top_level` and with `"some/path/file.ml.A"` in `in_submodule`.

That doesn't change the agenda as having a proper type to represent such code path and being able to access the sensible part rather than parsing a string is definitely an improvement over the current API.

I just wanted to correct my previous statement as `path` isn't as broken as I though it was.
